FROM ubuntu

# install common packages
RUN apt-get update
RUN apt-get -y install build-essential autoconf automake libtool curl unzip cmake pkg-config git 

# install protocol buffers
WORKDIR /libraries
RUN git clone https://github.com/protocolbuffers/protobuf.git
WORKDIR /libraries/protobuf
RUN git submodule update --init --recursive
RUN ./autogen.sh
RUN ./configure
RUN make 
RUN make install
RUN ldconfig

# install grpc
WORKDIR /libraries
RUN git clone https://github.com/grpc/grpc
WORKDIR /libraries/grpc
RUN git submodule update --init
RUN make
RUN make install

# install demo project
WORKDIR /app
COPY cpp_demo/cmake /app/cmake
RUN mkdir protosource
COPY cpp_demo/CMakeLists.txt .
COPY cpp_demo/main.cpp .
COPY cpp_demo/proto_generate.sh .
COPY cpp_demo/RPCServer.cpp .
COPY cpp_demo/RPCServer.h .
COPY protofiles/demo.proto .
RUN cmake .
RUN make

# run application
CMD ./demo